// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9jgCbV9y5PFZTBl60S6uaq3T_gLc9Npc',
    appId: '1:777700416476:web:89eecb1c9bc256e0ea4d19',
    messagingSenderId: '777700416476',
    projectId: 'my-flutter-app-4eb98',
    authDomain: 'my-flutter-app-4eb98.firebaseapp.com',
    storageBucket: 'my-flutter-app-4eb98.firebasestorage.app',
  );

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD96XzGRt01opDnORvKd_nsGfRE8pfCzZY',
    appId: '1:777700416476:android:034e0bcb9658ce0bea4d19',
    messagingSenderId: '777700416476',
    projectId: 'my-flutter-app-4eb98',
    storageBucket: 'my-flutter-app-4eb98.firebasestorage.app',
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3b6UuJwS8ykD69QqZG4kSnSFLsO5SKLs',
    appId: '1:777700416476:ios:3df961ef90d1ff48ea4d19',
    messagingSenderId: '777700416476',
    projectId: 'my-flutter-app-4eb98',
    storageBucket: 'my-flutter-app-4eb98.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static  FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3b6UuJwS8ykD69QqZG4kSnSFLsO5SKLs',
    appId: '1:777700416476:ios:3df961ef90d1ff48ea4d19',
    messagingSenderId: '777700416476',
    projectId: 'my-flutter-app-4eb98',
    storageBucket: 'my-flutter-app-4eb98.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static  FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9jgCbV9y5PFZTBl60S6uaq3T_gLc9Npc',
    appId: '1:777700416476:web:5f9d4d04f2275d60ea4d19',
    messagingSenderId: '777700416476',
    projectId: 'my-flutter-app-4eb98',
    authDomain: 'my-flutter-app-4eb98.firebaseapp.com',
    storageBucket: 'my-flutter-app-4eb98.firebasestorage.app',
  );
}
